# Menggunakan server FrankenPHP versi terbaru
FROM dunglas/frankenphp

# Mengatur agar server berjalan di port standar web (80)
ENV SERVER_NAME=":80"

# Memaksa server untuk menginstal dan mengaktifkan ekstensi MySQLi
RUN install-php-extensions mysqli pdo_mysql

# Menyalin seluruh file kodingan web RT Mas Fian ke dalam folder server
COPY . /app